/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define BUILD_API_VER 349

#define BUILD_FIX_VER 0

#undef PL_DEBUG_ABORT

#undef PL_HAVE_DBGHELP

#define PL_HAVE_EXECINFO

#define PL_HAVE_UNWIND

