/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once
#define USE_GL
#define HAVE_EGL

#define HAVE_GLFW_OPENGL

//#define HAVE_GLFW_VULKAN

#define HAVE_NUKLEAR

#define HAVE_SDL_OPENGL

//#define HAVE_SDL_VULKAN

