/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#ifndef WIN32
#define HAVE_EGL
#define HAVE_GLFW_OPENGL
//#define HAVE_SDL_OPENGL
#else
#define HAVE_GLFW_D3D11
#endif
#define HAVE_NUKLEAR

